### ISSUE TITLE
Machinist / Turrets

### ISSUE THREAD

**Issue by oscirus** [JBurlison/Pandaros.Settlers#13]
Seems like the machinist request specific leaves for the Matchlock turret. It won't use any leaf in the inventory, I believe it is requesting Taiga leaves, which the forester does not harvest.

The turrets don't seem to fire if there are blocks in certain locations. They work fine if they have a 360 degree view, but seems like if you put blocks on the immediate "back" (relative) it doesn't fire. Maybe it's a side the Machinist needs to access it from?

**Comment by JBurlison** [comment]
What version on the mod are you running? I should have fixed the blocking issue last release.

I will look into the laves issue. They should run on coal if you dont have the leaves.

**Comment by oscirus** [comment]
Ya, the machinists get stuck there asking for leaves but never leaving.
Sounds similar to the issue below.
But a leaf is a leaf? Shouldn't be requesting a specific leaf? If so,
definitely document that somewhere. Taiga leaves are hard to come by.

How do I check version of the mod? I'm on the Colony Empire public server -
should pull down latest that you put in.

**Comment by JBurlison** [comment]
ok they have the latest. I will look into it

**Comment by JBurlison** [comment]
Resolved: https://github.com/JBurlison/Pandaros.Settlers/commit/f48df8711f3ea367fb5e85e523949f6e6e08ee3e

**Comment by boyraad300** [comment]
issue not resolved but found the problem,
please replace line 143-144 of turret.cs with:
```C# 
                    if (machineState.Load < MachineState.MAX_LOAD[player])
                    {
                        foreach (var ammo in TurretSettings[machineState.MachineType].Ammo)
                        {
                            if (!stockpile.Contains(ammo))
                            {
                                retval = ammo.Type;
                            }
                        }
                    }

**Comment by JBurlison** [comment]
Humm it displays an Icon even though you have the materials?

I They way I have written it, It only dis plays the first because it runs through all the mats and if you dont have any at all it should show the icon.

So, you should only see the icon if you are out of all Fuel sources.

**Comment by boyraad300** [comment]
The line I referenced was in the reloading function but was still pulling the data for the icon from the refueling section. The solution I posted will cycle through the possible ammo and tell you which one is not currently in the stockpile (except for cases where you are missing both gunpowder and bullets)

**Comment by JBurlison** [comment]
OOo I see I mis understood.  My fault I will get this fixed!

**Comment by JBurlison** [comment]
Fixed : https://github.com/JBurlison/Pandaros.Settlers/commit/b4e1ba387b280a735a040f2c22ac964b88243d73
